{{ if eq (include "resource.vpa.enabled" .) "true" }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "zot.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zot.labels" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Chart.Name }}
        controlledResources:
          - cpu
          - memory
        maxAllowed:
          cpu: {{ .Values.resources.limits.cpu }}
          memory: {{ .Values.resources.limits.memory }}
        minAllowed:
          cpu: {{ .Values.resources.requests.cpu }}
          memory: {{ .Values.resources.requests.memory }}
        mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "zot.fullname" . }}
  updatePolicy:
    updateMode: Auto
{{ end }}
