{{- if .Values.route.enabled -}}
{{- $route := .Values.route -}}
{{- $fullName := include "zot.fullname" . -}}
{{- if and $route.backendTrafficPolicy $route.backendTrafficPolicy.enabled }}
{{- $policy := $route.backendTrafficPolicy }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ $route.name | default $fullName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "zot.labels" . | nindent 4 }}
    {{- with $policy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $policy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: {{ $route.kind | default "HTTPRoute" }}
      name: {{ $route.name | default $fullName }}
  {{- with $policy.connection }}
  connection:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
