{{- if and .Values.mountConfig .Values.configFiles }}
---
apiVersion: v1
kind: ConfigMap
metadata:
<<<<<<< HEAD
  name: "{{ .Release.Name }}-config"
=======
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
>>>>>>> 0a62307986a73a4a68031b53e54a6d73c2b57e2f
data:
{{- range $key, $val := .Values.configFiles }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}
