{{- if and .Values.persistence .Values.pvc .Values.pvc.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name | default (printf "%s-pvc" .Release.Name) }}
spec:
  accessModes:
  - {{ .Values.pvc.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage | default "8Gi" }}
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
{{- end }}

{{- if or (.Capabilities.APIVersions.Has "kyverno.io/v2alpha1/PolicyException") (eq .Values.pvc.policyException.enforce true) }}
---
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: allow-pvc-{{ .Release.Name | quote }}
  {{- if (.Values.pvc.policyException).namespace }}
  namespace: {{ .Values.pvc.policyException.namespace }}
  {{- end }}
  labels:
    {{- include "zot.labels" . | nindent 4 }}
spec:
  background: true
  exceptions:
  - policyName: restrict-volume-types
    ruleNames:
    - autogen-restricted-volumes
  match:
    any:
    - resources:
        kinds:
        - Deployment
        names:
        - {{ include "zot.fullname" . }}
        namespaces:
        - "{{ .Release.Namespace }}"
{{- end }}
