<<<<<<< HEAD
{{- if .Values.serviceMonitor.enabled }}
apiVersion: "monitoring.coreos.com/v1"
=======
{{- if .Values.metrics }}
{{- if .Values.metrics.enabled }}
{{- if .Values.metrics.serviceMonitor }}
{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
>>>>>>> 0c36953fba9c00cb117d06505ca97a7ecd4a07fe
kind: ServiceMonitor
metadata:
  name: {{ include "zot.fullname" . }}
  labels:
<<<<<<< HEAD
    {{- include "zot.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "zot.labels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace | quote }}
  endpoints:
  - port: zot
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    honorLabels: {{ .Values.serviceMonitor.honorLabels }}
    {{- with .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.serviceMonitor.basicAuth }}
    basicAuth:
      password:
        name: {{ include "zot.fullname" $ }}-sm-auth
        key: password
      username:
        name: {{ include "zot.fullname" $ }}-sm-auth
        key: username
    {{- end }}
{{- if .Values.serviceMonitor.basicAuth }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zot.fullname" . }}-sm-auth
  labels:
    {{- include "zot.labels" . | nindent 4 }}
data:
  username: {{ print .Values.serviceMonitor.basicAuth.username | b64enc }}
  password: {{ print .Values.serviceMonitor.basicAuth.password | b64enc }}
=======
    app.kubernetes.io/component: metrics
spec:
  {{- if .Values.metrics.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.metrics.serviceMonitor.jobLabel }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zot.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: zot
      {{- if .Values.metrics.serviceMonitor.interval }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.path }}
      path: {{ .Values.metrics.serviceMonitor.path }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.scheme }}
      scheme: {{ .Values.metrics.serviceMonitor.scheme }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
{{- end }}
>>>>>>> 0c36953fba9c00cb117d06505ca97a7ecd4a07fe
{{- end }}
{{- end }}
