{{- if .Values.metrics }}
{{- if .Values.metrics.enabled }}
{{- if .Values.metrics.serviceMonitor }}
{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "zot.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/component: metrics
    {{- include "zot.labels" . | nindent 4 }}
spec:
  {{- if .Values.metrics.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.metrics.serviceMonitor.jobLabel }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zot.labels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  endpoints:
    - port: zot
      {{- if .Values.metrics.serviceMonitor.interval }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
      {{- end }}
      honorLabels: {{ .Values.metrics.serviceMonitor.honorLabels }}
      {{- if .Values.metrics.serviceMonitor.path }}
      path: {{ .Values.metrics.serviceMonitor.path }}
      {{- end }}
      {{- if .Values.metrics.serviceMonitor.scheme }}
      scheme: {{ .Values.metrics.serviceMonitor.scheme }}
      {{- end }}
<<<<<<< HEAD
      {{- with .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.basicAuth }}
      basicAuth:
        password:
          name: {{ include "zot.fullname" $ }}-sm-auth
          key: password
        username:
          name: {{ include "zot.fullname" $ }}-sm-auth
          key: username
      {{- end }}
{{- if .Values.metrics.serviceMonitor.basicAuth }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zot.fullname" . }}-sm-auth
  labels:
    {{- include "zot.labels" . | nindent 4 }}
data:
  username: {{ print .Values.metrics.serviceMonitor.basicAuth.username | b64enc }}
  password: {{ print .Values.metrics.serviceMonitor.basicAuth.password | b64enc }}
{{- end }}
=======
      {{- if .Values.metrics.serviceMonitor.basicAuth }}
      basicAuth:
        password:
          name: {{ .Values.metrics.serviceMonitor.basicAuth.secretName }}
          key: {{ .Values.metrics.serviceMonitor.basicAuth.passwordKey | default ("password") }}
        username:
          name: {{ .Values.metrics.serviceMonitor.basicAuth.secretName }}
          key: {{ .Values.metrics.serviceMonitor.basicAuth.usernameKey | default ("username") }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
>>>>>>> b8f527ab0efa859fc848c555f92f407143a2ea6e
{{- end }}
{{- end }}
{{- end }}
{{- end }}
