{{- if .Values.serviceMonitor.enabled }}
apiVersion: "monitoring.coreos.com/v1"
kind: ServiceMonitor
metadata:
  name: {{ include "zot.fullname" . }}
  labels:
    {{- include "zot.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "zot.labels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace | quote }}
  endpoints:
  - port: zot
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    honorLabels: {{ .Values.serviceMonitor.honorLabels }}
    {{- with .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.serviceMonitor.basicAuth }}
    basicAuth:
      password:
        name: {{ include "zot.fullname" $ }}-sm-auth
        key: password
      username:
        name: {{ include "zot.fullname" $ }}-sm-auth
        key: username
    {{- end }}
{{- if .Values.serviceMonitor.basicAuth }}
---
apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "zot.fullname" . }}-sm-auth
  labels:
    {{- include "zot.labels" . | nindent 4 }}
data:
  username: {{ print .Values.serviceMonitor.basicAuth.username | b64enc }}
  password: {{ print .Values.serviceMonitor.basicAuth.password | b64enc }}
{{- end }}
{{- end }}
