{{ if eq (include "resource.vpa.enabled" .) "true" }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "zot.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zot.labels" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Chart.Name }}
        controlledResources:
          - cpu
          - memory
        minAllowed:
          cpu: {{ .Values.resources.requests.cpu }}
          memory: {{ .Values.resources.requests.memory }}
        maxAllowed:
          cpu: {{ .Values.giantswarm.verticalPodAutoscaler.maxAllowed.cpu }}
          memory: {{ .Values.giantswarm.verticalPodAutoscaler.maxAllowed.memory }}
        mode: Auto
  targetRef:
  {{- if .Values.persistence }}
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "zot.fullname" . }}
  {{- else }}
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "zot.fullname" . }}
  {{- end }}
  updatePolicy:
    updateMode: Auto
{{ end }}
