name: Auto upgrade the chart from upstream

on: workflow_dispatch

jobs:
  run_upgrade:
    name: Run the upgrade script
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git config --global user.email "subtree-bot@github.com" && git config --global user.name "Subtree Update Bot"
      - run: .github/workflows/ci-update-to-latest.sh
