name: Auto upgrade the chart from upstream

on:
  schedule:
    - cron: "15 13 * * 1,2,3,4,5"
  workflow_dispatch: {}

jobs:
  run_upgrade:
    name: Run the upgrade script
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      # GITHUB_TOKEN: ${{ secrets.TAYLORBOT_GITHUB_ACTION }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git config --global user.email "action@github.com" && git config --global user.name "GitHub Action"
      - run: .github/workflows/ci-update-to-latest.sh
