name: Auto upgrade the chart from upstream

on: workflow_dispatch

jobs:
  run_upgrade:
    name: Run the upgrade script
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -la
      - run: .github/workflows/ci-update-to-latest.sh
