name: Auto upgrade the chart from upstream

on: workflow_dispatch

jobs:
  run_upgrade:
    name: Run the upgrade script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: .github/workflows/ci-update-to-latest.sh
